<?php

namespace App\Console\Commands;

use App\Services\Feedback\ActionAnalyzerService;
use App\Services\Feedback\GitHubPrCreator;
use Illuminate\Console\Command;
use Illuminate\Support\Carbon;

/**
 * Semi-auto feedback loop killer feature cho cuộc thi:
 *   php artisan ocr:analyze-actions --since=7days --min-count=5 [--pr]
 *
 * Flow:
 *   1. Aggregate ocr_user_actions unanalyzed (LEFT JOIN ocr_extractions để có doc_type)
 *   2. Gọi LLM với skill `feedback-to-skill-refiner` prompt → patterns + diffs
 *   3. Sinh markdown report dạng reports/skill-update-YYYY-MM-DD-HHMMSS.md
 *   4. (Nếu --pr) Tạo branch + commit report + push + gh pr create → output PR URL
 *   5. Mark all analyzed actions với analyzed_at = NOW
 *
 * Skill: .claude/skills/feedback-to-skill-refiner/SKILL.md
 */
class AnalyzeActions extends Command
{
    protected $signature = 'ocr:analyze-actions
                            {--since=7days : Time range (e.g. 7days, 30days, 24hours)}
                            {--min-count=5 : Minimum action count per pattern to include}
                            {--pr : Tạo GitHub PR thay vì chỉ write markdown report}
                            {--dry-run : Không mark analyzed_at, không tạo PR — chỉ preview output}';

    protected $description = 'Phân tích implicit actions của KSNB → đề xuất skill update qua GitHub PR (semi-auto feedback loop)';

    public function handle(ActionAnalyzerService $analyzer): int
    {
        $since = $this->parseSince($this->option('since'));
        $minCount = (int) $this->option('min-count');
        $dryRun = (bool) $this->option('dry-run');
        $createPr = (bool) $this->option('pr');

        $this->info("Analyzing KSNB actions since {$since->toIso8601String()} (min_count={$minCount})...");

        $result = $analyzer->analyze($since, $minCount);

        $this->newLine();
        $this->info("=== Summary ===");
        $this->table(['Metric', 'Value'], [
            ['Actions analyzed', $result['stats']['actions_analyzed']],
            ['Patterns detected', $result['summary']['total_patterns_detected'] ?? 0],
            ['Actionable (create_pr)', $result['summary']['actionable'] ?? 0],
            ['Deferred (needs_more_data)', $result['summary']['deferred'] ?? 0],
            ['Out-of-scope (needs_new_skill)', $result['summary']['needs_new_skill'] ?? 0],
            ['LLM latency', $result['stats']['llm_latency_ms'] . 'ms'],
            ['LLM tokens (in/out)', $result['stats']['llm_input_tokens'] . ' / ' . $result['stats']['llm_output_tokens']],
        ]);

        if (empty($result['patterns'])) {
            $this->warn('No actionable patterns found. Đặt --min-count thấp hơn hoặc đợi thêm KSNB actions.');
            return self::SUCCESS;
        }

        // Markdown report
        $markdown = $this->buildMarkdownReport($result, $since);
        $stamp = now()->format('Y-m-d-His');
        $reportFile = "skill-update-{$stamp}.md";
        $reportAbsPath = base_path("reports/{$reportFile}");
        @mkdir(dirname($reportAbsPath), 0755, true);
        file_put_contents($reportAbsPath, $markdown);
        $this->newLine();
        $this->info("Report written: {$reportAbsPath}");

        if ($dryRun) {
            $this->warn('--dry-run: actions NOT marked analyzed, no PR created. Run lại không --dry-run để commit.');
            return self::SUCCESS;
        }

        // Optionally create GitHub PR
        if ($createPr) {
            try {
                $gh = new GitHubPrCreator(base_path());
                $gh->ensureGhAvailable();
                $branch = $gh->createBranch($stamp);

                $patches = [];
                foreach ($result['patterns'] as $p) {
                    if (! empty($p['proposed_diff']) && ! empty($p['target_runtime_file'])) {
                        $patches[] = [
                            'target_path' => $p['target_runtime_file'],
                            'diff' => $p['proposed_diff'],
                        ];
                    }
                }
                $gh->applyDiffs($patches);

                $commitMsg = sprintf(
                    "[ai-major] skill: refine %d patterns from KSNB feedback (%s)\n\nReport: reports/%s\nPatches: reports/patches/ (engineer apply manually)\nGenerated by ocr:analyze-actions\n\nCo-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>",
                    count($result['patterns']),
                    $stamp,
                    $reportFile,
                );
                $gh->commitAndPush($branch, $commitMsg, []);

                $prBody = "## KSNB Feedback Analysis\n\n"
                    . "**Generated:** " . now()->toIso8601String() . "\n"
                    . "**Actions analyzed:** {$result['stats']['actions_analyzed']}\n"
                    . "**Patterns detected:** {$result['summary']['total_patterns_detected']}\n\n"
                    . "## Engineer review checklist\n\n"
                    . "- [ ] Review pattern observations + hypotheses\n"
                    . "- [ ] Apply patches từ `reports/patches/*.patch`\n"
                    . "- [ ] Update skill `.md` files theo decision tree\n"
                    . "- [ ] Run tests: `vendor/bin/phpunit`\n"
                    . "- [ ] Approve & merge\n\n"
                    . "## Patterns\n\n"
                    . $this->buildPrPatternsSection($result);

                $prTitle = "[Skill update] {$result['summary']['total_patterns_detected']} patterns from KSNB feedback ({$stamp})";

                $url = $gh->createPr($prTitle, $prBody);
                $gh->switchBack('main');

                $this->newLine();
                $this->info("PR created: {$url}");
            } catch (\Throwable $e) {
                $this->error("PR creation failed: {$e->getMessage()}");
                $this->warn('Report markdown vẫn được tạo. Engineer có thể manually commit + tạo PR.');
            }
        }

        $marked = $analyzer->markAnalyzed($since);
        $this->info("Marked {$marked} actions as analyzed_at = NOW.");

        return self::SUCCESS;
    }

    private function parseSince(string $spec): Carbon
    {
        if (preg_match('/^(\d+)days?$/', $spec, $m)) {
            return now()->subDays((int) $m[1]);
        }
        if (preg_match('/^(\d+)hours?$/', $spec, $m)) {
            return now()->subHours((int) $m[1]);
        }
        return Carbon::parse($spec);
    }

    private function buildMarkdownReport(array $result, Carbon $since): string
    {
        $md = "# Skill Update Report — " . now()->format('Y-m-d H:i') . "\n\n";
        $md .= "Analyzed **{$result['stats']['actions_analyzed']}** KSNB actions since {$since->format('Y-m-d')}.\n";
        $md .= "**LLM:** {$result['stats']['llm_provider']} / {$result['stats']['llm_model']}\n";
        $md .= "**Latency:** {$result['stats']['llm_latency_ms']}ms\n";
        $md .= "**Tokens:** {$result['stats']['llm_input_tokens']} in / {$result['stats']['llm_output_tokens']} out\n\n";

        $md .= "## Summary\n\n";
        $md .= "- Patterns detected: **{$result['summary']['total_patterns_detected']}**\n";
        $md .= "- Actionable: {$result['summary']['actionable']}\n";
        $md .= "- Deferred (needs_more_data): {$result['summary']['deferred']}\n";
        $md .= "- Out-of-scope (needs_new_skill): {$result['summary']['needs_new_skill']}\n\n";

        $md .= "## Actionable patterns\n\n";
        foreach ($result['patterns'] as $p) {
            $md .= "### {$p['pattern_id']} — {$p['category']} / {$p['severity']}\n\n";
            $md .= "**Observation:** {$p['observation']}\n\n";
            $md .= "**Hypothesis:** {$p['hypothesis']}\n\n";
            if (! empty($p['target_skill_file'])) {
                $md .= "**Target skill:** `{$p['target_skill_file']}`\n";
            }
            if (! empty($p['target_runtime_file'])) {
                $md .= "**Target runtime:** `{$p['target_runtime_file']}`\n";
            }
            $md .= "**Confidence:** " . number_format(($p['confidence'] ?? 0) * 100, 1) . "%\n";
            $md .= "**Suggested action:** `{$p['suggested_action']}`\n\n";

            if (! empty($p['suggested_skill_name'])) {
                $md .= "**Suggested new skill (human design):**\n";
                $md .= "- Name: `{$p['suggested_skill_name']}`\n";
                $md .= "- Scope: {$p['suggested_skill_scope']}\n\n";
            }

            if (! empty($p['proposed_diff'])) {
                $md .= "**Proposed diff:**\n\n{$p['proposed_diff']}\n\n";
            }
            $md .= "**Engineer action:**\n";
            $md .= "- [ ] Review pattern\n";
            $md .= "- [ ] Apply diff\n";
            $md .= "- [ ] Reject — reason: ___\n\n";
            $md .= "---\n\n";
        }

        if (! empty($result['deferred'])) {
            $md .= "## Deferred (needs_more_data)\n\n";
            foreach ($result['deferred'] as $d) {
                $md .= "- **{$d['pattern_id']}** — {$d['reason']}\n";
            }
        }

        return $md;
    }

    private function buildPrPatternsSection(array $result): string
    {
        $section = '';
        foreach ($result['patterns'] as $p) {
            $section .= "### {$p['pattern_id']} ({$p['severity']})\n";
            $section .= "**{$p['observation']}**\n\n";
            $section .= "_{$p['hypothesis']}_\n\n";
            if (! empty($p['target_runtime_file'])) {
                $section .= "Target: `{$p['target_runtime_file']}`\n\n";
            }
        }
        return $section;
    }
}
