<?php

/**
 * Mapping snake_case key → label tiếng Việt cho KSNB UI.
 *
 * Tập hợp từ:
 *  - Stage 2 critical_fields per doc type ([app/Services/Ocr/Stage2VisionExtractorService.php](app/Services/Ocr/Stage2VisionExtractorService.php))
 *  - File khảo sát KSNB Section "Trường thông tin cần bóc tách"
 *  - Common variations (snake_case + English camelCase)
 *
 * Lookup logic ([App\Support\OcrFieldLabels::label()](app/Support/OcrFieldLabels.php)):
 *   1. Exact key match (case-sensitive)
 *   2. Fallback: ucfirst(str_replace('_', ' ', $key)) — humanized
 */
return [
    // ===== CCCD / CMND =====
    'so_cccd' => 'Số CCCD',
    'cccd_number' => 'Số CCCD',
    'cmnd_number' => 'Số CMND',
    'ho_ten' => 'Họ và tên',
    'ho_va_ten' => 'Họ và tên',
    'ngay_sinh' => 'Ngày sinh',
    'gioi_tinh' => 'Giới tính',
    'quoc_tich' => 'Quốc tịch',
    'dan_toc' => 'Dân tộc',
    'ton_giao' => 'Tôn giáo',
    'que_quan' => 'Quê quán',
    'noi_thuong_tru' => 'Nơi thường trú',
    'noi_dang_ky_thuong_tru' => 'Nơi đăng ký thường trú',
    'ngay_cap' => 'Ngày cấp',
    'noi_cap' => 'Nơi cấp',
    'co_quan_cap' => 'Cơ quan cấp',
    'co_gia_tri_den' => 'Có giá trị đến',
    'ngay_het_han' => 'Ngày hết hạn',
    'dac_diem_nhan_dang' => 'Đặc điểm nhận dạng',

    // ===== Passport =====
    'passport_number' => 'Số hộ chiếu',
    'so_passport' => 'Số hộ chiếu',
    'full_name' => 'Họ và tên',
    'surname' => 'Họ',
    'given_name' => 'Tên',
    'date_of_birth' => 'Ngày sinh',
    'place_of_birth' => 'Nơi sinh',
    'nationality' => 'Quốc tịch',
    'date_of_issue' => 'Ngày cấp',
    'place_of_issue' => 'Nơi cấp',
    'issuing_authority' => 'Cơ quan cấp',
    'expiry_date' => 'Ngày hết hạn',
    'sex' => 'Giới tính',

    // ===== CMND nước ngoài (national_id_foreign) — TQ/JP/KR/etc. =====
    'id_number' => 'Số CMND',
    'gender' => 'Giới tính',
    'ethnicity' => 'Dân tộc',

    // ===== Giấy phép kinh doanh (GPKD) =====
    'mst' => 'Mã số thuế',
    'tax_code' => 'Mã số thuế',
    'ma_so_doanh_nghiep' => 'Mã số doanh nghiệp',
    'ten_doanh_nghiep' => 'Tên doanh nghiệp',
    'ten_cong_ty' => 'Tên công ty',
    'ten_cong_ty_tieng_anh' => 'Tên công ty (tiếng Anh)',
    'dia_chi' => 'Địa chỉ',
    'dia_chi_tru_so' => 'Địa chỉ trụ sở',
    'dia_chi_tru_so_chinh' => 'Địa chỉ trụ sở chính',
    'nguoi_dai_dien' => 'Người đại diện pháp luật',
    'nguoi_dai_dien_phap_luat' => 'Người đại diện pháp luật',
    'chuc_vu' => 'Chức vụ',
    'ngay_thanh_lap' => 'Ngày thành lập',
    'ngay_cap_lan_dau' => 'Ngày cấp lần đầu',
    'nganh_nghe' => 'Ngành nghề kinh doanh',
    'nganh_nghe_kinh_doanh' => 'Ngành nghề kinh doanh',
    'von_dieu_le' => 'Vốn điều lệ',
    'loai_hinh_doanh_nghiep' => 'Loại hình doanh nghiệp',
    'so_giay_phep' => 'Số giấy phép',

    // ===== Hợp đồng (VI/EN/ZH) =====
    'so_hop_dong' => 'Số hợp đồng',
    'ngay_hop_dong' => 'Ngày hợp đồng',
    'contract_number' => 'Số hợp đồng',
    'contract_date' => 'Ngày hợp đồng',
    'ben_a' => 'Bên A',
    'ben_b' => 'Bên B',
    'ngay_ky' => 'Ngày ký',
    'signing_date' => 'Ngày ký',
    'gia_tri' => 'Giá trị hợp đồng',
    'gia_tri_hop_dong' => 'Giá trị hợp đồng',
    'value' => 'Giá trị',
    'total_value' => 'Tổng giá trị',
    'party_a' => 'Bên A (Party A)',
    'party_b' => 'Bên B (Party B)',
    'party_a_name' => 'Tên Bên A',
    'party_b_name' => 'Tên Bên B',
    'party_a_address' => 'Địa chỉ Bên A',
    'party_b_address' => 'Địa chỉ Bên B',
    'party_a_representative' => 'Người đại diện Bên A',
    'party_b_representative' => 'Người đại diện Bên B',
    'party_a_tax_code' => 'MST Bên A',
    'party_b_tax_code' => 'MST Bên B',
    'mst_ben_a' => 'MST Bên A',
    'mst_ben_b' => 'MST Bên B',
    'dia_chi_ben_a' => 'Địa chỉ Bên A',
    'dia_chi_ben_b' => 'Địa chỉ Bên B',
    'nguoi_dai_dien_ben_a' => 'Người đại diện Bên A',
    'nguoi_dai_dien_ben_b' => 'Người đại diện Bên B',
    // Terms
    'payment_term' => 'Điều khoản thanh toán',
    'delivery_term' => 'Điều khoản giao hàng',
    'shipment_term' => 'Điều khoản vận chuyển',
    'liability_term' => 'Điều khoản trách nhiệm',
    'dieu_khoan_thanh_toan' => 'Điều khoản thanh toán',
    'dieu_khoan_giao_hang' => 'Điều khoản giao hàng',
    'dieu_khoan_van_chuyen' => 'Điều khoản vận chuyển',
    'dieu_khoan_trach_nhiem' => 'Điều khoản trách nhiệm',
    'contract_term' => 'Thời hạn hợp đồng',
    'thoi_han_hop_dong' => 'Thời hạn hợp đồng',
    'effective_date' => 'Ngày hiệu lực',
    // Goods
    'danh_muc_hang_hoa' => 'Danh mục hàng hóa',
    'mo_ta_hang_hoa' => 'Mô tả hàng hóa',
    'so_luong' => 'Số lượng',
    'don_gia' => 'Đơn giá',
    'tong_gia_tri' => 'Tổng giá trị',
    'don_vi_do_luong' => 'Đơn vị đo lường',
    'unit_of_measurement' => 'Đơn vị đo lường',
    'item_description' => 'Mô tả mặt hàng',
    // Payment info
    'payment_bank_name' => 'Ngân hàng thanh toán',
    'payment_bank_account_name' => 'Chủ tài khoản',
    'payment_bank_account_number' => 'Số tài khoản',
    'ngan_hang_thanh_toan' => 'Ngân hàng thanh toán',
    'chu_tai_khoan' => 'Chủ tài khoản',
    'thong_tin_tai_khoan_thu_huong' => 'Tài khoản thụ hưởng',

    // ===== Hóa đơn / Invoice =====
    'invoice_number' => 'Số hóa đơn',
    'invoice_date' => 'Ngày hóa đơn',
    'total_amount' => 'Tổng tiền',
    'subtotal' => 'Tiền trước thuế',
    'tax_amount' => 'Tiền thuế',
    'tax_rate' => 'Thuế suất',
    'currency' => 'Loại tiền',
    'seller' => 'Bên bán',
    'buyer' => 'Bên mua',
    'seller_name' => 'Tên bên bán',
    'buyer_name' => 'Tên bên mua',
    'seller_tax_code' => 'MST bên bán',
    'buyer_tax_code' => 'MST bên mua',
    'unit_price' => 'Đơn giá',
    'quantity' => 'Số lượng',
    'goods_description' => 'Mô tả hàng hóa',
    'model' => 'Model',

    // ===== Tờ khai hải quan =====
    'declaration_number' => 'Số tờ khai',
    'declaration_date' => 'Ngày tờ khai',
    'pre_declaration_number' => 'Số tờ khai sơ bộ',
    'importer' => 'Bên nhập khẩu',
    'exporter' => 'Bên xuất khẩu',
    'hs_code' => 'Mã HS',
    'gross_weight_kg' => 'Trọng lượng cả bì (kg)',
    'net_weight_kg' => 'Trọng lượng tịnh (kg)',
    'number_of_packages' => 'Số kiện',
    'package_type' => 'Loại bao bì',
    'transport_method' => 'Phương thức vận tải',
    'transaction_method' => 'Phương thức giao dịch',
    'origin_country_region' => 'Nước xuất xứ',
    'destination_country_region' => 'Nước đến',
    'final_destination_country_region' => 'Nước nhận cuối',
    'port_of_destination' => 'Cảng đến',
    'customs_office_of_exit' => 'Hải quan cửa khẩu xuất',
    'supervision_method' => 'Phương thức giám sát',
    'exemption_nature' => 'Tính chất miễn thuế',
    'trade_country_region' => 'Nước trao đổi thương mại',
    'domestic_source_location' => 'Nơi nguồn hàng trong nước',
    'transport_vehicle_name_voyage_number' => 'Tên phương tiện + số chuyến',
    'contract_agreement_number' => 'Số hợp đồng',
    'declaration_unit' => 'Đơn vị khai báo',
    'declaration_unit_agreement' => 'Đơn vị khai báo (ủy thác)',
    'entrusting_party' => 'Bên ủy thác',
    'entrusted_party' => 'Bên nhận ủy thác',
    'container_number' => 'Số container',
    'unit_price_total_price_currency' => 'Đơn giá / Tổng giá / Tiền tệ',
    'bill_of_lading_number' => 'Số vận đơn',

    // ===== Vận đơn / Bill of Lading =====
    'bl_number' => 'Số vận đơn',
    'shipper' => 'Người gửi (Shipper)',
    'consignee' => 'Người nhận (Consignee)',
    'notify_party' => 'Bên thông báo',
    'vessel_name' => 'Tên tàu',
    'voyage_number' => 'Số chuyến tàu',
    'port_of_loading' => 'Cảng xếp hàng',
    'port_of_discharge' => 'Cảng dỡ hàng',
    'place_of_receipt' => 'Nơi nhận hàng',
    'place_of_delivery' => 'Nơi giao hàng',
    'bl_date' => 'Ngày vận đơn',
    'carrier' => 'Hãng vận chuyển',

    // ===== Điều lệ AML / Power of attorney / Labor / Financial =====
    'document_number' => 'Số văn bản',
    'principal' => 'Bên ủy quyền',
    'attorney' => 'Bên nhận ủy quyền',
    'scope' => 'Phạm vi ủy quyền',
    'employer' => 'Người sử dụng lao động',
    'employee' => 'Người lao động',
    'position' => 'Chức danh / vị trí',
    'salary' => 'Lương',
    'reporting_period' => 'Kỳ báo cáo',
    'total_revenue' => 'Tổng doanh thu',
    'net_profit' => 'Lợi nhuận sau thuế',
    'total_assets' => 'Tổng tài sản',
    'total_liabilities' => 'Tổng nợ phải trả',
    'equity' => 'Vốn chủ sở hữu',

    // ===== Bill of Lading extra =====
    'gross_weight' => 'Trọng lượng cả bì',
    'net_weight' => 'Trọng lượng tịnh',
    'place_of_loading' => 'Nơi xếp hàng',

    // ===== Legal doc / AML extra =====
    'subject' => 'Chủ đề',
    'parties' => 'Các bên',
    'company_name' => 'Tên công ty',
    'company_tax_code' => 'MST công ty',

    // ===== Power of attorney extra =====
    'document_date' => 'Ngày văn bản',
    'principal_address' => 'Địa chỉ bên ủy quyền',
    'attorney_address' => 'Địa chỉ bên nhận ủy quyền',
    'witnesses' => 'Người làm chứng',
    'work_scope' => 'Phạm vi công việc',

    // ===== Labor contract extra =====
    'contract_start_date' => 'Ngày bắt đầu hợp đồng',
    'contract_end_date' => 'Ngày kết thúc hợp đồng',
    'work_location' => 'Địa điểm làm việc',
    'working_hours' => 'Giờ làm việc',
    'employer_address' => 'Địa chỉ công ty',
    'employee_id_number' => 'Số CMND/CCCD/HC nhân viên',
    'employer_mst' => 'MST công ty',
    'payment_method' => 'Hình thức trả lương',
    'payment_date' => 'Ngày trả lương',
    'trial_period_salary' => 'Lương thử việc',
    'trial_period_duration' => 'Thời gian thử việc',
    'benefits' => 'Phúc lợi',
    'job_scope' => 'Phạm vi công việc',
    'job_description' => 'Mô tả công việc',

    // ===== Financial report extra =====
    'cost_of_goods_sold' => 'Giá vốn hàng bán',
    'operating_expenses' => 'Chi phí hoạt động',
    'gross_profit' => 'Lợi nhuận gộp',
    'report_date' => 'Ngày báo cáo',
    'auditor' => 'Đơn vị kiểm toán',

    // ===== Generic / shared =====
    'email' => 'Email',
    'phone' => 'Số điện thoại',
    'phone_number' => 'Số điện thoại',
    'sdt' => 'Số điện thoại',
    'address' => 'Địa chỉ',
    'account_number' => 'Số tài khoản',
    'account_name' => 'Tên tài khoản',
    'bank_name' => 'Tên ngân hàng',
    'swift_code' => 'Mã SWIFT',
    'website' => 'Website',
    'fax' => 'Số fax',
];
